name: Swarm Upload

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.3'
      - name: Build
        run: |
          npm ci --prefix themes/swarm-blog
          npm run build --prefix themes/swarm-blog
          hugo -D --gc
          npx -y pagefind --source public
      - name: Upload to Swarm
        uses: ethersphere/swarm-actions/upload-dir@v0.7.0
        id: upload
        with:
          dir: ./public
          index-document: index.html
          bee-url: https://bee-1.fairdatasociety.org
          timeout: 300000
          deferred: false

      - name: Setup feed
        uses: ethersphere/swarm-actions/write-feed@v0.7.0
        id: feed
        with:
          reference: ${{ steps.upload.outputs.reference }}
          topic: "swarm-blog"
          bee-url: https://bee-1.fairdatasociety.org
          signer: c869821c02560960441332cc004b56a03cb8c9521888d056233b1b961c0959fd

      - uses: ethersphere/swarm-actions/reference-to-cid@latest
        id: cid
        with:
          reference: ${{ steps.feed.outputs.manifest }}

      - run: |
          echo 'Chunk Reference: ${{ steps.upload.outputs.reference }}'
          echo 'Feed Reference: ${{ steps.feed.outputs.reference }}'
          echo 'Feed Manifest: ${{ steps.feed.outputs.manifest }}'
          echo 'Feed Bzz.link: https://${{ steps.cid.outputs.cid }}.bzz.link'
